default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: event_development

test:
  <<: *default
  database: event_test

production:
  <<: *default
  database: event_production
