# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37a5bee709c1c67ba9e9be1edba1156d3dc99db8dc28a86ef2155b514bdfd45e7f6869f6e17ff275f5aeb9616ca7bf2f2804e4f18d01eb4919f5ebf0076ca224

test:
  secret_key_base: 469c97fd5c97c6fbe25e78fedcc7c05413a2cc9454ef4b0da0467cc507fe6a3c25b1975a5d3cc84b6c600aa8665ef4c40cc70c996376bd5baa7bcb26e19d9327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
